# Generated by Django 5.0.3 on 2024-03-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_leaders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='social_links',
            field=models.JSONField(),
        ),
    ]
