# Generated by Django 5.0.3 on 2024-03-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_leaders', '0002_alter_speaker_social_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='social_links',
        ),
        migrations.AddField(
            model_name='speaker',
            name='github_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='linkedin_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='x_link',
            field=models.URLField(blank=True),
        ),
    ]
