# Generated by Django 5.0.3 on 2024-03-30 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_leaders', '0003_remove_speaker_social_links_speaker_github_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('virtual', 'virtual'), ('in-person', 'in-person'), ('hybrid', 'hybrid')], default='virtual', max_length=200),
        ),
        migrations.CreateModel(
            name='Event_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('registered_students', models.IntegerField()),
                ('attendees', models.IntegerField()),
                ('college_name', models.CharField(max_length=255)),
                ('collaboring_college', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('virtual', 'virtual'), ('in-person', 'in-person'), ('hybrid', 'hybrid')], default='virtual', max_length=200)),
                ('platform', models.CharField(max_length=255)),
                ('media_link', models.URLField(blank=True)),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_leaders.speaker')),
            ],
        ),
    ]
